### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by line0**
This PR updates all dependencies to current packages versions and includes (only) the necessary API usage changes to keep _dynamodb_ working. However, since _dynamodb_ exposes _Joi_ on its own API and _Joi_ recently dropped support for node < ~8~10, this should be considered a breaking change.

Gets rid of all 31 vulnerabilities (8 low, 5 moderate, 16 high, 2 critical) previously reported by `npm audit`.

~~**Not yet ready to merge** because even though all tests succeed, I have not yet given this a real world test drive.~~

### CODE REVIEW

**Comment by JacopoDaeli** [comment]
Any updates on this?

**Comment by line0** [comment]
@JacopoDaeli these changes have been working well in our applications for quite a few weeks now.

**Comment by line0** [comment]
updated the PR with latest dependency version, now targets node >= 10.

**Comment by MickL** [comment]
Should we fork instead? Seems like this is no more maintained?

**Comment by MickL** [comment]
@baseprime @ryanfitz

**Comment by MickL** [comment]
@line0 I tested your PR but it is not working. You can reproduce by running `npm run test`. Error:

> Error: Cannot find module 'async'
> Require stack:
    > - /myPath/dynamodb/lib/utils.js
    > - /myPath/dynamodb/lib/expressions.js
    > - /myPath/dynamodb/lib/query.js
    > - /myPath/dynamodb/lib/table.js
    > - /myPath/dynamodb/test/test-helper.js
    > - /myPath/dynamodb/test/batch-test.js
    > - /myPath/dynamodb/node_modules/mocha/lib/mocha.js
    > - /myPath/dynamodb/node_modules/mocha/index.js
    > - /myPath/dynamodb/node_modules/mocha/bin/_mocha

**Comment by baseprime** [comment]
@MickL This package _is_ maintained, PRs need to include tests.

**Comment by MickL** [comment]
@baseprime I dont know what you mean by include tests? Doesnt circle-ci run automatically on each PR? And then it should comment the issue if the tests have run successful.

**Comment by line0** [comment]
@baseprime what other tests do you need? The existing unit & integration tests pass, one test was added to validate an issue that came up and no additional functionality has been added.

**Comment by baseprime** [comment]
@line0 Can you run your tests and paste the results here? Tests for this PR aren't passing on CircleCI.

**Comment by JacopoDaeli** [comment]
@line0 I confirm. These changes working fine for me too.

**Comment by JacopoDaeli** [comment]
@line0 @MickL I'm currently using your fork for a project I am building and it works just fine.

**Comment by MickL** [comment]
@baseprime Could you please make CircleCI results public in GitHub repositories? So everyone can see them and everyone can contribute if a test fails.

**Comment by line0** [comment]
updated dependencies again. here's the test results:

[dynamodb-tests-g7eb5434-20200921.log](https://github.com/baseprime/dynamodb/files/5256041/dynamodb-tests-g7eb5434-20200921.log)

**Comment by baseprime** [comment]
Merged latest CI config with https://github.com/line0/dynamodb/pull/4

**Pull request merged**
