### PR TITLE
Feat security fixes

### PR DESCRIPTION
**Pull request by romanbalayan**
Update package dependencies to address vulnerability issues on #40

### CODE REVIEW

**Comment by baseprime** [comment]
This PR is good but it's not passing tests. Maybe it's an issue with `sinon@v1.12.x`?

```
> npm test


✔ No problems


  ․ Batch #getItems should get items by hash key: 5ms
  ․ Batch #getItems should get items by hash key using promises: 1ms
  ․ Batch #getItems should get items by hash and range key: 0ms
  ․ Batch #getItems should not modify passed in keys: 85ms
  ․ Batch #getItems should get items by hash key with consistent read: 0ms
  ․ Batch #getItems should get items by hash key with projection expression: 1ms
  ․ Batch #getItems should get items when encounters retryable excpetion: 1ms
  ․ Batch #getItems should return error: 0ms
  ․ Batch #getItems should promisify an error: 0ms
  ․ expressions #parse should parse single SET action: 0ms
  ․ expressions #parse should parse multiple SET actions: 0ms
  ․ expressions #parse should parse ADD action: 0ms
  ․ expressions #parse should parse REMOVE action: 0ms
  ․ expressions #parse should parse DELETE action: 0ms
  ․ expressions #parse should parse ADD and SET actions: 0ms
  ․ expressions #parse should parse multiple actions: 0ms
  ․ expressions #parse should return null actions when given null: 0ms
  ․ expressions #parse should return null actions when given empty string: 0ms
  ․ expressions #serializeUpdateExpression should return single SET action: 0ms
  ․ expressions #serializeUpdateExpression should return multiple SET actions: 0ms
  ․ expressions #serializeUpdateExpression should return SET and ADD actions: 0ms
  1) expressions #serializeUpdateExpression should return single DELETE action
  ․ expressions #serializeUpdateExpression should return single REMOVE action: 0ms
  ․ expressions #serializeUpdateExpression should return single REMOVE action when value is set to empty string: 0ms
  ․ expressions #serializeUpdateExpression should return empty actions when passed empty object: 0ms
  ․ expressions #serializeUpdateExpression should return empty actions when passed null: 0ms
  ․ expressions #stringify should return single SET action: 0ms
  ․ expressions #stringify should return single SET action when param is a string: 0ms
  ․ expressions #stringify should return single SET action when other actions are null: 0ms
  ․ expressions #stringify should return multiple SET actions: 0ms
  ․ expressions #stringify should return SET and ADD actions: 0ms
  ․ expressions #stringify should return stringified ALL actions: 0ms
  ․ expressions #stringify should return empty string when passed empty actions: 0ms
  ․ expressions #stringify should return empty string when passed null actions: 0ms
  ․ expressions #stringify should return empty string when passed empty object: 0ms
  ․ expressions #stringify should return empty string when passed null: 0ms
  ․ expressions #stringify should result from stringifying a parsed string should equal original string: 0ms
  ․ dynamo #define should return model: 2ms
  ․ dynamo #define should throw when using old api: 1ms
  ․ dynamo #define should have config method: 0ms
  ․ dynamo #define should configure table name as accounts: 1ms
  ․ dynamo #define should return new account item: 0ms
  ․ dynamo #models should be empty: 1ms
  ․ dynamo #models should contain single model: 0ms
  ․ dynamo #model should return defined model: 1ms
  ․ dynamo #model should return null: 0ms
  ․ dynamo model config should configure set dynamodb driver: 0ms
  ․ dynamo model config should configure set dynamodb driver: 1ms
  ․ dynamo model config should set document client: 1ms
  ․ dynamo model config should globally set dynamodb driver for all models: 1ms
  ․ dynamo model config should continue to use globally set dynamodb driver: 1ms
  ․ dynamo #createTables should create single definied model: 2ms
  ․ dynamo #createTables should return error: 0ms
  ․ dynamo #createTables should reject an error with promises: 0ms
  ․ dynamo #createTables should create model without callback: 1ms
  ․ dynamo #createTables should return error when waiting for table to become active: 1ms
  ․ item JSON.stringify should only serialize attrs: 0ms
  ․ item #save should return error: 2ms
  ․ item #update should return item: 1ms
  ․ item #update should resolve to an item with a promise: 0ms
  ․ item #update should return error: 1ms
  ․ item #update should return null: 0ms
  ․ ParallelScan should return error: 2ms
  ․ ParallelScan should stream error: 0ms
  ․ ParallelScan should promisify an error: 1ms
  ․ Query #exec should run query against table: 2ms
  ․ Query #exec should run query against table using promises: 2ms
  ․ Query #exec should return error: 2ms
  ․ Query #exec should stream error: 2ms
  ․ Query #exec should promisify an error: 3ms
  ․ Query #exec should stream data after handling retryable error: 1003ms
  ․ Query #limit should set the limit: 0ms
  ․ Query #limit should throw when limit is zero: 0ms
  ․ Query #filterExpression should set filter expression: 0ms
  ․ Query #expressionAttributeValues should set expression attribute values: 1ms
  ․ Query #expressionAttributeNames should set expression attribute names: 0ms
  ․ Query #projectionExpression should set projection expression: 0ms
  ․ Query #usingIndex should set the index name to use: 3ms
  ․ Query #usingIndex should create key condition for global index hash key: 1ms
  ․ Query #consistentRead should set Consistent Read to true: 0ms
  ․ Query #consistentRead should set Consistent Read to true when passing no args: 0ms
  ․ Query #consistentRead should set Consistent Read to false: 0ms
  ․ Query #attributes should set array attributes to get: 1ms
  ․ Query #attributes should set single attribute to get: 1ms
  ․ Query #order should set scan index forward to true: 0ms
  ․ Query #order should set scan index forward to false: 0ms
  ․ Query #startKey should set start Key: 0ms
  ․ Query #select should set select Key: 1ms
  ․ Query #ReturnConsumedCapacity should set return consumed capacity Key to passed in value: 0ms
  ․ Query #ReturnConsumedCapacity should set return consumed capacity Key: 0ms
  ․ Query #where should have hash key and range key equals clauses: 1ms
  ․ Query #where should have equals clause: 0ms
  ․ Query #where should have less than or equal clause: 0ms
  ․ Query #where should have less than clause: 0ms
  ․ Query #where should have greater than or equal clause: 0ms
  ․ Query #where should have greater than clause: 1ms
  ․ Query #where should have begins with clause: 0ms
  ․ Query #where should have between clause: 0ms
  ․ Query #where should support multiple clauses on same attribute: 1ms
  ․ Query #filter should have equals clause: 1ms
  ․ Query #filter should have exists clause: 0ms
  ․ Query #filter should have not exists clause: 0ms
  ․ Query #filter should have between clause: 0ms
  ․ Query #filter should have IN clause: 0ms
  ․ Query #filter should support multiple filters on same attribute: 0ms
  ․ Query #loadAll should set load all option to true: 2ms
  ․ Scan #exec should call run scan on table: 1ms
  ․ Scan #exec should return LastEvaluatedKey: 0ms
  ․ Scan #exec should return error: 0ms
  ․ Scan #exec should run scan after encountering a retryable exception: 0ms
  ․ Scan #limit should set the limit: 0ms
  ․ Scan #limit should throw when limit is zero: 0ms
  ․ Scan #attributes should set array attributes to get: 0ms
  ․ Scan #attributes should set single attribute to get: 0ms
  ․ Scan #startKey should set start Key to hash: 1ms
  ․ Scan #startKey should set start Key to hash + range: 0ms
  ․ Scan #select should set select Key: 0ms
  ․ Scan #ReturnConsumedCapacity should set return consumed capacity Key to passed in value: 0ms
  ․ Scan #ReturnConsumedCapacity should set return consumed capacity Key: 0ms
  ․ Scan #segment should set both segment and total segments keys: 0ms
  ․ Scan #where should have equals clause: 0ms
  ․ Scan #where should have not equals clause: 0ms
  ․ Scan #where should have less than or equal clause: 0ms
  ․ Scan #where should have less than clause: 0ms
  ․ Scan #where should have greater than or equal clause: 0ms
  ․ Scan #where should have greater than clause: 0ms
  ․ Scan #where should have not null clause: 0ms
  ․ Scan #where should have null clause: 0ms
  ․ Scan #where should have contains clause: 0ms
  ․ Scan #where should not pass a number set when making contains call: 0ms
  ․ Scan #where should have not contains clause: 0ms
  ․ Scan #where should have in clause: 0ms
  ․ Scan #where should have begins with clause: 0ms
  ․ Scan #where should have between clause: 0ms
  ․ Scan #where should have multiple filters: 0ms
  ․ Scan #where should have multiple filters on the same attribute: 0ms
  ․ Scan #where should convert date to iso string: 0ms
  ․ Scan #loadAll should set load all option to true: 0ms
  ․ Scan #filterExpression should set filter expression: 0ms
  ․ Scan #expressionAttributeValues should set expression attribute values: 0ms
  ․ Scan #expressionAttributeNames should set expression attribute names: 0ms
  ․ Scan #projectionExpression should set projection expression: 0ms
  ․ schema setup should set hash key: 0ms
  ․ schema setup should set hash and range key: 0ms
  ․ schema setup should set table name to string: 0ms
  ․ schema setup should set table name to function: 0ms
  ․ schema setup should add timestamps to schema: 1ms
  ․ schema setup should add timestamps with custom names to schema: 0ms
  ․ schema setup should only add createdAt timestamp : 1ms
  ․ schema setup should only add updatedAt timestamp : 0ms
  ․ schema setup should only add custom created timestamp : 1ms
  ․ schema setup should throw error when hash key is not present: 1ms
  ․ schema setup should setup local secondary index when both hash and range keys are given: 1ms
  ․ schema setup should setup local secondary index when only range key is given: 0ms
  ․ schema setup should throw when local index rangeKey isnt present: 1ms
  ․ schema setup should throw when local index hashKey does not match the tables hashKey: 0ms
  ․ schema setup should setup global index: 0ms
  ․ schema setup should throw when global index hashKey is not present: 0ms
  2) schema setup should parse schema data types
  3) schema #stringSet should set as string set
  4) schema #numberSet should set as number set
  5) schema #binarySet should set as binary set
  ․ schema #uuid should set as uuid with default uuid function: 0ms
  ․ schema #timeUUID should set as TimeUUID with default v1 uuid function: 0ms
  ․ schema #validate should return no err for string: 3ms
  ․ schema #validate should return no error for valid date object: 0ms
  ․ schema #applyDefaults should apply default values: 1ms
  ․ schema #applyDefaults should return result of default functions: 1ms
  ․ Serializer #buildKeys should handle string hash key: 0ms
  ․ Serializer #buildKeys should handle number hash key: 0ms
  ․ Serializer #buildKeys should handle date hash key: 1ms
  ․ Serializer #buildKeys should handle string hash and range key: 0ms
  ․ Serializer #buildKeys should handle number hash and range key: 0ms
  ․ Serializer #buildKeys should handle object containing the hash key: 0ms
  ․ Serializer #buildKeys should handle local secondary index keys: 0ms
  ․ Serializer #buildKeys should handle global secondary index keys: 0ms
  ․ Serializer #buildKeys should handle boolean global secondary index key: 0ms
  ․ Serializer #serializeItem should serialize string attribute: 0ms
  ․ Serializer #serializeItem should serialize number attribute: 0ms
  ․ Serializer #serializeItem should serialize binary attribute: 1ms
  ․ Serializer #serializeItem should serialize number attribute with value zero: 0ms
  ․ Serializer #serializeItem should serialize boolean attribute: 1ms
  ․ Serializer #serializeItem should serialize date attribute: 0ms
  6) Serializer #serializeItem should serialize string set attribute
  7) Serializer #serializeItem should serialize single string set attribute
  8) Serializer #serializeItem should number set attribute
  9) Serializer #serializeItem should single number set attribute
  10) Serializer #serializeItem should serialize binary set attribute
  11) Serializer #serializeItem should serialize single binary set attribute
  ․ Serializer #serializeItem should serialize uuid attribute: 1ms
  ․ Serializer #serializeItem should serialize TimeUUId attribute: 0ms
  ․ Serializer #serializeItem should return null: 0ms
  ․ Serializer #serializeItem should serialize string attribute for expected: 0ms
  ․ Serializer #serializeItem should serialize string attribute for expected exists false: 0ms
  12) Serializer #serializeItem should serialize nested attributes
  ․ Serializer #serializeItem should return empty when serializing null value: 0ms
  ․ Serializer #deserializeItem should return string value: 0ms
  ․ Serializer #deserializeItem should return values in StringSet: 0ms
  ․ Serializer #deserializeItem should return values in NumberSet: 0ms
  ․ Serializer #deserializeItem should return null when item is null: 0ms
  ․ Serializer #deserializeItem should return nested values: 0ms
  ․ Serializer #serializeItemForUpdate should serialize string attribute: 0ms
  ․ Serializer #serializeItemForUpdate should serialize number attribute: 0ms
  13) Serializer #serializeItemForUpdate should serialize three attributes
  ․ Serializer #serializeItemForUpdate should serialize null value to a DELETE action: 1ms
  ․ Serializer #serializeItemForUpdate should not serialize hashkey attribute: 0ms
  ․ Serializer #serializeItemForUpdate should not serialize hashkey and rangeKey attributes: 0ms
  14) Serializer #serializeItemForUpdate should serialize add operations
  15) Serializer #serializeItemForUpdate should serialize delete operations
  ․ table #get should get item by hash key: 0ms
  ․ table #get should get item by hash key with a promise: 0ms
  ․ table #get should get item by hash and range key: 1ms
  ․ table #get should get item by hash key and options: 0ms
  ․ table #get should get item by hashkey, range key and options: 1ms
  ․ table #get should get item from dynamic table by hash key: 0ms
  ․ table #get should return error: 0ms
  ․ table #create should create valid item: 1ms
  ․ table #create should call apply defaults: 1ms
  16) table #create should omit null values
  ․ table #create should omit empty values: 1ms
  ․ table #create should create item with createdAt timestamp: 0ms
  ․ table #create should create item with custom createdAt attribute name: 0ms
  ․ table #create should create item without createdAt param: 0ms
  ․ table #create should create item with expected option: 1ms
  ․ table #create should create item with no callback: 0ms
  ․ table #create should return validation error: 0ms
  ․ table #create should create item with condition expression on hashkey when overwrite flag is false: 2ms
  ․ table #create should create item with condition expression on hash and range key when overwrite flag is false: 1ms
  ․ table #create should create item without condition expression when overwrite flag is true: 1ms
  ․ table #update should update valid item: 1ms
  ․ table #update should update with passed in options: 1ms
  ․ table #update should update merge update expressions when passed in as options: 1ms
  ․ table #update should update valid item with a promise: 1ms
  ․ table #update should return error: 1ms
  ․ table #update should reject an error with a promise: 0ms
  ․ table #query should return query object: 0ms
  ․ table #scan should return scan object: 0ms
  ․ table #destroy should destroy valid item: 0ms
  ․ table #destroy should take optional params: 0ms
  ․ table #destroy should parse and return attributes: 1ms
  ․ table #destroy should accept hash and range key: 1ms
  ․ table #destroy should accept hashkey rangekey and options: 0ms
  ․ table #destroy should serialize expected option: 1ms
  ․ table #destroy should call delete item with a promise: 0ms
  ․ table #destroy should call delete item with hash key, options and no callback: 1ms
  ․ table #createTable should create table with hash key: 0ms
  ․ table #createTable should create table with range key: 0ms
  ․ table #createTable should create table with secondary index: 1ms
  ․ table #createTable should create table with global secondary index: 1ms
  ․ table #createTable should create table with global secondary index: 1ms
  ․ table #describeTable should make describe table request: 1ms
  ․ table #updateTable should make update table request: 1ms
  ․ table #updateTable should make update table request with a promise: 1ms
  ․ table #deleteTable should make delete table request: 0ms
  ․ table #deleteTable should make delete table request with a promise: 0ms
  ․ table #tableName should return given name: 0ms
  ․ table #tableName should return table name set on schema: 0ms
  ․ table #tableName should return table name returned from function on schema: 1ms
  ․ table hooks #destroy should call after hook: 0ms
  ․ table hooks #create should call before hooks: 1ms
  ․ table hooks #create should return error when before hook returns error: 1ms
  ․ table hooks #create should call after hook: 1ms
  ․ table hooks #update should call before hook: 1ms
  ․ table hooks #update should return error when before hook returns error: 1ms
  ․ table hooks #update should call after hook: 0ms

  249 passing (2s)
  16 failing

  1) expressions #serializeUpdateExpression should return single DELETE action:
     AssertionError: expected undefined to deeply equal 'String'
      at Context.<anonymous> (test/expressions-test.js:228:44)

  2) schema setup should parse schema data types:

      AssertionError: expected { Object (foo, date, ...) } to deeply equal { Object (foo, date, ...) }
      + expected - actual

         "date": "DATE"
         "flag": "BOOL"
         "foo": "S"
         "items": "L"
      -  "nums": [
      -    {
      -      "invalids": [null]
      -      "type": [null]
      -    }
      -  ]
      +  "nums": "NS"
       }
      
      at Context.<anonymous> (test/schema-test.js:280:32)

  3) schema #stringSet should set as string set:

      AssertionError: expected { Object (email, names) } to deeply equal { email: 'S', names: 'SS' }
      + expected - actual

       {
         "email": "S"
      -  "names": [
      -    {
      -      "invalids": [null]
      -      "type": [null]
      -    }
      -  ]
      +  "names": "SS"
       }
      
      at Context.<anonymous> (test/schema-test.js:315:32)

  4) schema #numberSet should set as number set:

      AssertionError: expected { Object (email, nums) } to deeply equal { email: 'S', nums: 'NS' }
      + expected - actual

       {
         "email": "S"
      -  "nums": [
      -    {
      -      "invalids": [null]
      -      "type": [null]
      -    }
      -  ]
      +  "nums": "NS"
       }
      
      at Context.<anonymous> (test/schema-test.js:334:32)

  5) schema #binarySet should set as binary set:

      AssertionError: expected { Object (email, pics) } to deeply equal { email: 'S', pics: 'BS' }
      + expected - actual

       {
         "email": "S"
      -  "pics": [
      -    {
      -      "type": [null]
      -    }
      -    {
      -      "invalids": [null]
      -      "type": [null]
      -    }
      -  ]
      +  "pics": "BS"
       }
      
      at Context.<anonymous> (test/schema-test.js:353:32)

  6) Serializer #serializeItem should serialize string set attribute:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:301:23)

  7) Serializer #serializeItem should serialize single string set attribute:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:319:23)

  8) Serializer #serializeItem should number set attribute:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:337:24)

  9) Serializer #serializeItem should single number set attribute:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:355:24)

  10) Serializer #serializeItem should serialize binary set attribute:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:373:22)

  11) Serializer #serializeItem should serialize single binary set attribute:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:391:22)

  12) Serializer #serializeItem should serialize nested attributes:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:501:28)

  13) Serializer #serializeItemForUpdate should serialize three attributes:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:647:30)

  14) Serializer #serializeItemForUpdate should serialize add operations:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:724:29)

  15) Serializer #serializeItemForUpdate should serialize delete operations:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/serializer-test.js:745:29)

  16) table #create should omit null values:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at F.test (test/table-test.js:340:20)
      at deepEqual (node_modules/sinon/lib/sinon/util/core.js:126:26)
      at deepEqual (node_modules/sinon/lib/sinon/util/core.js:176:22)
      at deepEqual (node_modules/sinon/lib/sinon/util/core.js:176:22)
      at Object.deepEqual (node_modules/sinon/lib/sinon/util/core.js:176:22)
      at Function.matches (node_modules/sinon/lib/sinon/spy.js:277:27)
      at matchingFake (node_modules/sinon/lib/sinon/spy.js:43:30)
      at Function.invoke (node_modules/sinon/lib/sinon/spy.js:146:32)
      at DocumentClient.proxy [as put] (node_modules/sinon/lib/sinon/spy.js:74:30)
      at module.exports.Table.sendRequest (lib/table.js:64:18)
      at lib/table.js:213:10
      at node_modules/async/lib/async.js:52:16
      at Immediate._onImmediate (node_modules/async/lib/async.js:1206:34)



make: *** [test-unit] Error 16
npm ERR! Test failed.  See above for more details.
```

**Comment by baseprime** [comment]
@romanbalayan

**Comment by romanbalayan** [comment]
@baseprime,

Sorry, will try to get back to this.

**Comment by romanbalayan** [comment]
Hi @baseprime,

What node / sinon version should we be supporting? I'm using nodev8.11, sinon v1.12.2, and im getting all success on the tests?

**Comment by baseprime** [comment]
Duplicate of #70

**Pull request closed without merging**
