### PR TITLE
Updated aws-sdk

### PR DESCRIPTION
**Pull request by soliveira-nascent**
See this issue: https://github.com/baseprime/dynamodb/issues/16

Related to this PR: https://github.com/baseprime/dynamodb/pull/11

### CODE REVIEW

**Comment by soliveira-nascent** [comment]
This is an upgrade. `2.2.x` means we'll only get the latest **patch** version of AWS SDK `2.2`. The latest version of AWS SDK is actually `2.139.0` (see: https://github.com/aws/aws-sdk-js/releases)

Furthermore, by adding the `^` symbol, we're saying we always want the latest minor or patch release of major version 2. In other words, it it will match `2.x.x`.

**Comment by blinkylights23** [comment]
This should probably get approved - as the submitter points out, it's an upgrade not a downgrade (and aws-sdk before 2.6.x breaks webpack).

**Comment by baseprime** [comment]
@blinkylights23 @soliveira-nascent Can you please add test results? None of the tests are passing with `aws-sdk@2.139` or `aws-sdk@2.186`.

**Comment by baseprime** [comment]
@blinkylights23 @soliveira-nascent Tests pass in `aws-sdk@2.186`, please see 3ee894f3732b9d2b875c57d7d4033d08406348fd

**Pull request closed without merging**
